name: Generate metrics

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  habits:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate coding habits facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ github.token }}
          user: okturan
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_from: 25
          plugin_habits_days: 14
          config_timezone: Europe/Tirane
          delay: 0
          output_action: commit
          committer_branch: output
          committer_message: Update metrics
          plugins_errors_fatal: yes
